name: PHP Metrics - PR Quality Gate

on:
  pull_request:
    branches-ignore: ["main", "dev"]
    paths:
      - "**/*.php"
      - ".github/workflows/phpmetrics-diff.yml"
jobs:
  formatters:
    uses: ITinternalDiMartino/ci-workflows/.github/workflows/phpmetrics-diff.yml@main
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
