name: Pint & Prettier auto fix

on:
  workflow_call:
    inputs:
      node-version:
        description: "Versione di Node.js"
        required: false
        default: "22"
        type: string
    secrets:
      GH_TOKEN:
        required: true

permissions:
  contents: write
  pull-requests: write

jobs:
  php-code-styling:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          ref: ${{ github.head_ref }}

      - name: Configure Composer Authentication
        run: composer config --global --auth github-oauth.github.com ${{ secrets.GH_TOKEN }}

      - name: Install PHP dependencies
        run: composer install --no-interaction --no-progress --prefer-dist

      - name: Run Pint check
        run: ./vendor/bin/pint --test

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: ${{ inputs.node-version }}
          cache: npm

      - name: Install Node dependencies
        run: npm ci

      - name: Run Prettier check
        run: npx prettier --check .
