name: Run Laravel Tests

on:
  workflow_call:

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      matrix:
        php: ["8.2"]
      fail-fast: false

    name: PHP ${{ matrix.php }}

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: tests
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_ROOT_PASSWORD: ""
        ports:
          - "3306:3306"
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
          --health-start-period=30s

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: vendor
          key: composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: composer-

      - name: Setup PHP and Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug
          tools: composer
          extensions: json, dom, curl, libxml, mbstring
          ini-values: memory_limit=512M, max_execution_time=180, display_errors=On

      - name: Install PHP Dependencies
        run: composer install --no-interaction --prefer-dist --no-progress

      - name: Environment configuration
        run: |
          cp .env.example .env
          php artisan key:generate
          php artisan config:clear

      - name: Run Migrations
        run: php artisan migrate --force

      - name: Run Tests
        run: php artisan test --parallel
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: tests
          DB_USERNAME: root
          DB_PASSWORD:

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-php-${{ matrix.php }}
          path: |
            storage/logs/*
            coverage/*
          retention-days: 7
          if-no-files-found: warn
