name: Pint Check

on:
  workflow_call:

jobs:
  pint-check:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Install PHP dependencies
        run: composer install --no-interaction --no-progress --prefer-dist

      - name: Run Pint check
        run: ./vendor/bin/pint --test
