name: Fix Prettier Code Style

on:
  workflow_call:
    inputs:
      node-version:
        description: "Versione di Node.js"
        required: false
        default: "22"
        type: string

permissions:
  contents: write
  pull-requests: write

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          cache: npm

      - name: Install Node dependencies
        run: npm ci

      - name: Run Prettier
        run: npx prettier --write .

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: "style: prettier auto fix"
